version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.5
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MESSAGE_MAX_BYTES=2097152

volumes:
  kafka_data:
    driver: local